# Generated by Django 3.0.3 on 2020-07-26 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200726_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 18, 54, 41, 765888, tzinfo=utc)),
        ),
    ]
