# Generated by Django 3.0.3 on 2020-07-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200727_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='pic',
        ),
    ]
