# Generated by Django 3.0.3 on 2020-07-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200727_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pic',
            new_name='coverpic',
        ),
    ]
